spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/product_schema
    username: postgres
    password: root
  flyway:
    baseline-on-migrate: true
  application:
    name: serviceProduct
server:
  port: 8081